version: "3.9"  # optional since v1.27.0
services:
  relay:
    container_name: iToi_relay
    image: relay:latest
    volumes:
      - type: bind
        source: ./config
        target: /etc/config
      - type: bind
        source: ./data
        target: /data
      - type: bind
        source: ./keystore
        target: /keystore
    environment:
      - RELAY_CONFIG=/etc/config/icon_to_icon_config.json
    restart: always
